# Conditional Probability - Lab

## Introduction

In order to be ready for real world applications of probability, it is important to understand what happens when probabilities are not independent. Very often, the probability of a certain event depends on other events happening! Let's see how this all works in this lab.

## Objectives

You will be able to:

- Understand and explain the conditional probability - $P(A \cap B) = P(A \mid B) P(B)$
- Use the multiplication rule to find the probability of the intersection of two events
- Apply the techniques learned in the lesson to simple problems

## Exercise 1
A coin is tossed and a single 6-sided dice is rolled. Find the probability of landing on the head side of the coin and rolling a 3 on the dice.

In [1]:
coin_heads=1/2
three_on_die = 1/6

In [2]:
both = coin_heads*three_on_die
both

0.08333333333333333

## Exercise 2


After conducting a survey, one of the outcomes was that 8 out of 10 of the surey subjects liked chocolate chip cookies. If three survey subjects are chosen at random **with replacement**, what is the probability that all three like chocolate chip cookies?

In [3]:
all_three_like = (8/10)**3
all_three_like

0.5120000000000001

## Exercise 3
70% of your friends like chocolate flavored ice cream , and 35% like chocolate AND like strawberry flavors.

What percent of those who like chocolate also like strawberry?

In [4]:
print(.35/.7)

0.5


50% of your friends who like chocolate also like strawberry

## Exercise 4
What is the probability of drawing 2 consecutive aces from a deck of cards. 

In [5]:
print(4/52*3/51)

0.004524886877828055


## Exercise 5
In a manufacturing factory that produces a certain product, there are 100 units of the product, 5 of which are defective. We pick three units from the 100 units at random. 

What is the probability that none of them are defective?
Hint: Use the chain rule here!

In [6]:
print(95/100*94/99*93/98)

0.8559987631416202


## Exercise 6

Let's consider the example where 2 dice are thrown. Given that **at least one** of the dice has come up on a number higher than 4, what is the probability that the sum is 8?

Let $i,j$ be the numbers shown on the dice. The events $A$ and $B$ are described below:

* **Event $A$ is when either $i$ or $j$ is 5 or 6** (keep an eye on either - or)
* **Event $B$ is when $i + j = 8$**


* What is the size of sample space $\Omega$ ?
* What is $P(A \cap B)$ ?
* What is $P(A)$ ?
* Use above to calculate $P(B \mid A)$

In [22]:
import numpy as np


In [25]:
two_die = []


In [26]:
for  i in range(1,7):
    for j in range(1,7):
        two_die.append([i,j])
    
    
    

In [27]:
two_die = np.array(two_die)


In [34]:
five = two_die==5

In [35]:
six = two_die==6

In [59]:
six.shape

(36, 2)

In [64]:
six[1][0]

False

In [38]:
five_or_six = np.array([five, six])

In [48]:
five_or_six = []

In [72]:
for i, value in enumerate(five):
    if five[i][0] or five[i][1] or six[i][0] or six[i][1]:
        
        five_or_six.append(True)
    else:
        five_or_six.append(False)


In [73]:
np.array(five_or_six)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False,  True,  True, False,
       False, False, False,  True,  True, False, False, False, False,
        True,  True, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [79]:
np.array(five_or_six).sum()/

40

In [29]:
two_die.sum(axis=1)


array([ 2,  3,  4,  5,  6,  7,  3,  4,  5,  6,  7,  8,  4,  5,  6,  7,  8,
        9,  5,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10, 11,  7,  8,  9, 10,
       11, 12])

In [30]:
two_die_eight = two_die.sum(axis=1)==8


In [31]:
two_die_eight


array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False])

In [32]:
prob_B = two_die_eight.sum()/len(two_die_eight)


In [33]:
prob_B


0.1388888888888889

In [19]:
prob_A_intersect_B = prob_A * prob_B
prob_A_intersect_B


0.09259259259259259

In [21]:
B_given_A = prob_A_intersect_B/prob_A
B_given_A



0.1388888888888889

In [ ]:
#counting is off in above logic but moving on

#There are 20 occurances where there is a 5 or a 6 - probability of B
#There are 4 occurances of those 20 that add up to eight
#prob of A given B is the probability of A and B divided by the probability of A

In [84]:
pA_given_b = (4./36)/(20./36)
pA_given_b 

0.19999999999999998

## Exercise 7

Let's consider a credit card example. At a supermarket, customers are selected randomly, the store owner recorded whether costumers owned a Visa card (event A) or an Amex credit card (event B). Some customers own both cards.
You can assume that:

- $P(A)$ = 0.5
- $P(B)$ = 0.4
- both $A$ and $B$ = 0.25.


With the knowledge we have about conditional probabilities, compute and interpret the following probabilities:

- $P(B \mid A)$
- $P(B' \mid A)$
- $P(A \mid B)$
- $P(A' \mid B)$


In [91]:
# Your solution
B_given_A = (.25)/(.5)
Bnot_given_A = 1-B_given_A
A_given_B = (.25)/(.4)
Anot_given_A = 1-A_given_B

B_given_A

0.5

In [92]:
Bnot_given_A

0.5

In [93]:
A_given_B

0.625

In [94]:
Anot_given_A

0.375

## Summary 

In this lab you practiced conditional probability and its theorem with some simple problems. The key takeaway from this lab is to be able to identify random events as dependent or independent and calculating the probability of their occurrence using appropriate methods. Next you'll learn about some more conditional probability axioms, building on the knowledge we have so far. 